steps:
  - task: AWSShellScript@1
    inputs:
      scriptType: "inline"
      inlineScript: |
        $XA_WRAPPER yarn affected:deploy $(affected.affectedNxParams)
    displayName: "[workspace] deploy"
