steps:
  - task: AWSShellScript@1
    inputs:
      scriptType: "inline"
      inlineScript: |
        $XA_WRAPPER  yarn affected:destroy $(affected.affectedNxParams)
    displayName: "[workspace] destroy"
    condition: succeeded()
