changesetBaseRefs:
  - main
  - origin/main
  - develop
  - origin/develop

nodeLinker: pnp

npmScopes:
  everymile-idp:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://everymile-idp-116517182856.d.codeartifact.eu-west-1.amazonaws.com/npm/${DELIVERY_STAGE:-beta}-npm-publish/"
    npmRegistryServer: "https://everymile-idp-116517182856.d.codeartifact.eu-west-1.amazonaws.com/npm/${DELIVERY_STAGE:-beta}-main/"

packageExtensions:
  "@apollo/client@^3.4.16":
    dependencies:
      react: "*"
  "@aws-sdk/client-cognito-identity-provider@3.171.0":
    dependencies:
      aws-crt: 1.14.5
  "@aws-sdk/client-dynamodb@3.170.0":
    dependencies:
      aws-crt: 1.14.5
  "@aws-sdk/client-eventbridge@3.170.0":
    dependencies:
      "@aws-sdk/signature-v4-crt": 3.170.0
      aws-crt: 1.14.5
  "@aws-sdk/client-sqs@3.170.0":
    dependencies:
      aws-crt: 1.14.5
  "@aws-sdk/client-sso@3.170.0":
    dependencies:
      aws-crt: 1.14.5
  "@aws-sdk/client-sso@3.171.0":
    dependencies:
      aws-crt: 1.14.5
  "@aws-sdk/client-sts@3.170.0":
    dependencies:
      aws-crt: 1.14.5
  "@aws-sdk/client-sts@3.171.0":
    dependencies:
      aws-crt: 1.14.5
  "@nerdwallet/apollo-cache-policies@^2.7.0":
    dependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
  "@nrwl/cli@13.10.1":
    dependencies:
      "@nrwl/workspace": 13.10.1
  "@nrwl/cypress@13.10.1":
    dependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
      babel-loader: "*"
      dotenv: "*"
      typescript: ~4.5.5
      webpack: "*"
  "@nrwl/eslint-plugin-nx@13.10.1":
    dependencies:
      eslint: "*"
      nx: 13.10.1
  "@nrwl/jest@13.10.1":
    dependencies:
      "@nrwl/workspace": 13.10.1
      dotenv: ~10.0.0
      jest: 27.2.3
      nx: 13.10.1
      typescript: ~4.5.5
  "@nrwl/js@13.10.1":
    dependencies:
      tslib: "*"
  "@nrwl/linter@13.10.1":
    dependencies:
      typescript: ~4.5.5
  "@nrwl/node@13.10.1":
    dependencies:
      dotenv: "*"
      typescript: ~4.5.5
  "@nrwl/web@13.10.1":
    dependencies:
      typescript: ~4.5.5
  "@nrwl/workspace@13.10.1":
    dependencies:
      "@nrwl/tao": 13.10.1
      typescript: ~4.5.5
  "@yarn-tool/resolve-package@*":
    dependencies:
      "@types/node": ^18.0.1
  artillery@*:
    dependencies:
      "@oclif/errors": "*"
  aws-appsync-auth-link@^3.0.7:
    dependencies:
      graphql: ^14.0.0 || ^15.0.0
  aws-appsync-subscription-link@^3.1.0:
    dependencies:
      uuid: "*"
      graphql: ^14.0.0 || ^15.0.0
  chalk@5.1.0:
    dependencies:
      "#ansi-styles": npm:ansi-styles@6.1.1
      "#supports-color": npm:supports-color@9.2.3
  debug@*:
    dependencies:
      supports-color: "*"
  follow-redirects@*:
    dependencies:
      debug: "*"
  nx@^13.10.1:
    dependencies:
      "@nrwl/workspace": 13.10.1
      typescript: ~4.5.5
  serverless-newrelic-lambda-layers@*:
    dependencies:
      fs-extra: "*"
      https-proxy-agent: "*"
      lodash: "*"
      path: "*"
      semver: "*"
  serverless-webpack@*:
    dependencies:
      "@types/node": ^18.0.1
      typescript: ~4.5.5

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-wo9999rkspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"
  - path: .yarn/plugins/@yarnpkg/plugin-aws-codeartifact.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-aws-codeartifact/v0.9.2/bundles/@yarnpkg/plugin-aws-codeartifact.js"

supportedArchitectures:
  cpu:
    - x86
    - x64
    - current
  libc:
    - current
    - glibc
    - musl
  os:
    - linux
    - win32
    - current

yarnPath: .yarn/releases/yarn-3.2.2.cjs
