const mockOrderPayload = {
  amountPaid: 156.8,
  brandID: 3402,
  channelType: 5,
  currencyCode: "GBP",
  customerAddressLine1: "1 A 1 Haupt Strasse",
  customerAddressLine2: "Best State",
  customerCompany: "Taxi Co",
  customerCountryCode: "GB",
  customerCountyRegion: "Best Region",
  customerEmail: "testmailid1@gmail.com",
  customerFirstName: "Travis",
  customerLastName: "Bickle",
  customerPhone: undefined,
  customerPostalCode: "1234567",
  customerTownCity: "Berlin",
  datePurchased: "2022-06-24T15:33:15.629Z",
  orderItems: [
    {
      itemCost: 12,
      itemName: "Red Shoe Size 1",
      itemSKU: "red-shoe-size-1",
      quantity: 12,
      saleItemReference: "661f24ea-751c-4362-aefa-8db5826ce0de",
      vatRate: 0.2,
    },
  ],
  saleReference: "1234567",
  shippingAddressLine1: "1 A 1 Haupt Strasse",
  shippingAddressLine2: "Best State",
  shippingCompany: "Taxi Co",
  shippingCost: 20,
  shippingCountryCode: "GB",
  shippingCountyRegion: "Best Region",
  shippingEmail: "testmailid1@gmail.com",
  shippingFirstName: "Travis",
  shippingPhone: undefined,
  shippingLastName: "Bickle",
  shippingPostalCode: "1234567",
  shippingService: "NEXTDAY1",
  shippingTownCity: "Berlin",
  status: "completed",
};

export default mockOrderPayload;
