openapi: 3.0.0
info:
  title: The CaaS Private Orders API
  version: "1.0"
  description: |
    A document that details the Private-facing CaaS Orders API.

    #### What is the private API?

    The CaaS private API is designed to be facing trusted, internal applications.
servers:
  - url: "https"
    description: Production server (uses live data)
  - url: "https:///webhooks.dev.eu-w1.everymile.works"
    description: Dev server (uses test data)
  - url: "https:///webhooks.qa1.eu-w1.everymile.works"
    description: Qa1 server (uses test data)
paths:
  /cg/v1/orderstatuschanged:
    put:
      summary: |
        Receives order status change updates.
      tags:
        - Service
      security:
        - PskAuth: []
      responses:
        200:
          $ref: "#/components/responses/200EmptySuccessResponse"
        400:
          $ref: "#/components/responses/400BadRequest"
        401:
          $ref: "#/components/responses/401Unauthorised"
        500:
          description: Internal Server Error
      operationId: CGTokenIntrospect
      requestBody:
        $ref: "#/components/requestBodies/CGOrderStatusChangedRequestBody"
      x-internal: true
    parameters: []
  /ccp/v1/orderstatuschanged:
    put:
      summary: |
        Receives order status change updates.
      tags:
        - Service
      security:
        - PskAuth: []
      responses:
        200:
          $ref: "#/components/responses/200EmptySuccessResponse"
        400:
          $ref: "#/components/responses/400BadRequest"
        401:
          $ref: "#/components/responses/401Unauthorised"
        500:
          description: Internal Server Error
      operationId: CCPTokenIntrospect
      requestBody:
        $ref: "#/components/requestBodies/CCPOrderStatusChangedRequestBody"
      x-internal: true
    parameters: []
components:
  securitySchemes:
    PskAuth:
      type: http
      scheme: bearer
      bearerFormat: PSK
  schemas:
    CCPOrderStatusEnumType:
      type: string
      enum:
        - PLACED
        - SHIPPED
        - COMPLETED
        - CANCELLED
    CGOrderStatusEnumType:
      type: string
      enum:
        - incomplete
        - awaiting payment
        - new
        - cancelling
        - cancelled
        - cancel failed
        - dispatching
        - dispatched
        - partially dispatched
        - dispatch failed
        - returning
        - returned
        - partially returned
        - refunding
        - refunded
        - partially refunded
        - refund failed
    BadRequestErrorResponse:
      properties:
        error:
          type: object
          properties:
            requestParameters:
              type: object
            requestHeaders:
              type: object
            details:
              type: array
              items:
                type: object
                properties:
                  errorType:
                    type: string
                    enum: ["ValidationError"]
                  message:
                    type: string
                    example: "Expected string value, received a boolean"
                  metadata:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "invalid-type"
                      path:
                        type: array
                        items:
                          type: string
                          example: "status"
                required:
                  - errorType
                  - message
    CCPOrderStatusChangedRequestData:
      type: object
      required:
        - time
        - brand
        - orderId
        - status
      properties:
        time:
          type: string
          format: date-time
          description: A time when the order status information changed in their internal system. Expected date format is ISO_8601.
        brand:
          type: string
          description: This is OMS specific brand ID.
          example: 3402
        orderId:
          type: string
          description: The unique ID of the order.
        status:
          type: object
          required:
            - current
          properties:
            current:
              $ref: "#/components/schemas/CCPOrderStatusEnumType"
            previous:
              $ref: "#/components/schemas/CCPOrderStatusEnumType"
        delivery:
          type: object
          properties:
            trackingUrl:
              type: string
              format: url
            courier:
              type: object
              required:
                - companyName
              properties:
                companyName:
                  type: string
                  example: DHL
            expectedDeliveryWindow:
              type: object
              required:
                - value
                - type
              properties:
                value:
                  type: number
                  format: integer
                  minimum: 0
                type:
                  type: string
                  enum:
                    - days
                    - hours
                  default: days
            lineItems:
              type: array
              items:
                type: object
                required:
                  - sku
                  - status
                  - quantity
                  - dispatchedQuantity
                properties:
                  sku:
                    type: string
                  status:
                    allOf:
                      - $ref: "#/components/schemas/CCPOrderStatusEnumType"
                      - description: Items may be cancelled, shipped, still in processing somewhat independently of each other.
                  quantity:
                    type: number
                    format: integer
                    minimum: 1
                  dispatchedQuantity:
                    type: number
                    format: integer
                    minimum: 0
    CGOrderStatusChangedRequestData:
      type: object
      required:
        - datetime
        - organisationUnitId
        - externalId
        - status
      properties:
        datetime:
          type: string
          format: date-time
          description: A time when the order status information changed in their internal system. Expected date format is ISO_8601.
        organisationUnitId:
          type: string
          description: This is OMS specific brand ID.
          example: 3402
        externalId:
          type: string
          description: The unique ID of the order.
        status:
          $ref: "#/components/schemas/CGOrderStatusEnumType"
        delivery:
          type: object
          properties:
            trackingUrl:
              type: string
              format: url
            courier:
              type: object
              required:
                - companyName
              properties:
                companyName:
                  type: string
                  example: DHL
            expectedDeliveryWindow:
              type: object
              required:
                - value
                - type
              properties:
                value:
                  type: number
                  format: integer
                  minimum: 0
                type:
                  type: string
                  enum:
                    - days
                    - hours
                  default: days
            lineItems:
              type: array
              items:
                type: object
                required:
                  - sku
                  - status
                  - quantity
                  - dispatchedQuantity
                properties:
                  sku:
                    type: string
                  status:
                    allOf:
                      - $ref: "#/components/schemas/CGOrderStatusEnumType"
                      - description: Items may be cancelled, shipped, still in processing somewhat independently of each other.
                  quantity:
                    type: number
                    format: integer
                    minimum: 1
                  dispatchedQuantity:
                    type: number
                    format: integer
                    minimum: 0
  requestBodies:
    CCPOrderStatusChangedRequestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CCPOrderStatusChangedRequestData"
    CGOrderStatusChangedRequestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CGOrderStatusChangedRequestData"
  responses:
    200EmptySuccessResponse:
      description: Standard empty JSON object success response.
      content:
        application/json:
          schema:
            type: object
            example: {}
    400BadRequest:
      description: |
        A response given when the request is invalid, i.e. the request deviates from the given schema. Examples of
        this would be illegal request bodies, missing mandatory fields, incorrect value types for a given field etc.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequestErrorResponse"
    401Unauthorised:
      description: |
        A response given when the PSK is invalid, been tampered with, dont relate etc.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequestErrorResponse"
